import type { IpcApi } from './types';

// Dynamic imports so a plain browser never loads @tauri-apps/* in mock mode.
export const ipc: IpcApi =
  import.meta.env.VITE_MOCK_IPC === '1'
    ? (await import('./mock')).mockIpc
    : (await import('./tauri')).tauriIpc;

export type {
  AiAnalysis,
  AiAnalysisMode,
  AiAutonomy,
  AiAvailability,
  AiDiffTarget,
  AiResolveProposal,
  AiSummary,
  AppError,
  ApplyStashOutcome,
  AutoFetchSettings,
  BranchesSnapshot,
  BranchInfo,
  CherrypickOutcome,
  CommitDetails,
  CommitDiff,
  CommitMessageProposal,
  CommitResult,
  CompareDiff,
  CompareEndpoint,
  ConflictEntry,
  ConflictFile,
  ConflictKind,
  ConflictResolution,
  CreateStashResult,
  DiffLine,
  FileDiff,
  FileDiffHeader,
  FileStatus,
  GraphEdge,
  GraphLayout,
  GraphNode,
  GraphPrefs,
  HeadInfo,
  Hunk,
  IpcApi,
  LineKind,
  LineSelection,
  ListView,
  McpStatus,
  MergeOutcome,
  OpenRepoResult,
  RebaseOutcome,
  RecentRepo,
  RefKind,
  RefLabel,
  PaneWidths,
  RemoteBranchInfo,
  RepoChangedPayload,
  RepoInfo,
  RepoOpState,
  ResetMode,
  RevertOutcome,
  SessionState,
  StashEntry,
  StatusEntry,
  StatusSnapshot,
  SubmoduleInfo,
  SubmoduleStatus,
  Theme,
  UiSettings,
  UiSettingsPatch,
  Unsubscribe,
} from './types';
