import type { IpcApi } from './types';

// Dynamic imports so a plain browser never loads @tauri-apps/* in mock mode.
export const ipc: IpcApi =
  import.meta.env.VITE_MOCK_IPC === '1'
    ? (await import('./mock')).mockIpc
    : (await import('./tauri')).tauriIpc;

export type {
  AgentAsset,
  AgentAssetInput,
  AgentAssetInventory,
  AgentAssetKind,
  AiAnalysis,
  AiAnalysisMode,
  AiAsset,
  AiAssetInventory,
  AiAutonomy,
  AiGeneratedAsset,
  AiAvailability,
  AiDiffTarget,
  AiDigestRange,
  AiResolveProposal,
  AiSummary,
  AppError,
  ApplyStashOutcome,
  AssetContent,
  AssetFile,
  AssetIssue,
  AssetKind,
  AutoFetchSettings,
  BlameLine,
  BranchDeleteResult,
  BranchDeleteStatus,
  BranchesSnapshot,
  BranchInfo,
  CherrypickOutcome,
  CloneProgress,
  CommitDetails,
  CommitDiff,
  CommitMessageProposal,
  CommitResult,
  CompareDiff,
  CompareEndpoint,
  ConflictEntry,
  ConflictFile,
  ConflictKind,
  ConflictResolution,
  ContextProfile,
  CreateStashResult,
  DiffLine,
  DriftEntry,
  DriftReport,
  FileDiff,
  FileDiffHeader,
  FileHistoryEntry,
  FileStatus,
  FrontmatterField,
  GraphEdge,
  GraphLayout,
  GraphNode,
  GraphPrefs,
  HeadInfo,
  Hunk,
  IpcApi,
  IssueSeverity,
  LineKind,
  LineSelection,
  ListView,
  McpStatus,
  MergeOutcome,
  OpenRepoResult,
  RebaseOutcome,
  RecentRepo,
  RefKind,
  RefLabel,
  PaneWidths,
  ProfileActivation,
  ProfilePreviewEntry,
  ProfileStore,
  ProfileTarget,
  RebaseAction,
  RebaseTodoOp,
  RemoteBranchInfo,
  RemoteInfo,
  RepoChangedPayload,
  RepoInfo,
  RepoOpState,
  ResetMode,
  RevertOutcome,
  SessionState,
  StaleBranch,
  StaleReason,
  StaleReport,
  StashEntry,
  StatusEntry,
  StatusSnapshot,
  SubmoduleInfo,
  SubmoduleStatus,
  TargetWriteAction,
  TargetWriteResult,
  Theme,
  UiSettings,
  UiSettingsPatch,
  Unsubscribe,
  Validation,
  WorktreeInfo,
} from './types';
