//! P91 §8 — the `cmd.<name>` metric-key ALLOW-LIST: the exact set of `IpcApi`
//! method names.
//!
//! Audit F3: `log_append` carries `ipc.result` records straight from the webview,
//! and each one's `cmd` becomes a durable `cmd.<name>` histogram key in
//! `usage.json`. A SHAPE predicate (`metrics_keys::is_valid_cmd_name`) cannot
//! bound that — any well-shaped string passes — so membership in the real
//! command set is what decides. An unknown name drops the observation.
//!
//! GENERATED from the `IpcApi` interface declarations
//! (`src/ipc/types/ipc-api.ts`, `ipc-api-forge.ts`, `ipc-api-obs.ts`), which is
//! the set the frontend proxy can emit: `obs/ipcProxy.ts` uses the METHOD NAME as
//! `cmd`, so these are camelCase, not the snake_case Tauri command names.
//! `tests_metrics_cmds.rs` re-derives the list from those `.ts` files at test
//! time and fails on any drift, so adding an IPC method without regenerating this
//! table is caught by `cargo test`, not by a silently missing histogram.
//!
//! The §2.3-excluded methods (`logAppend`, `metricsSnapshot`, …) are present for
//! that exact-mirror property; the proxy never instruments them, so they can
//! never actually arrive.

/// Every `IpcApi` method name, sorted (binary search below depends on it).
pub(super) const KNOWN_CMDS: [&str; 201] = [
    "abortMerge",
    "ackRepoHooks",
    "activateProfile",
    "activateWorktreeProfile",
    "addRemote",
    "addSubmodule",
    "addWorktree",
    "addWorktreeWithChanges",
    "aiAnalyzeDiff",
    "aiApplyResolution",
    "aiCancelRun",
    "aiChangelog",
    "aiComposeCommits",
    "aiDigest",
    "aiExplainLine",
    "aiGenerateAsset",
    "aiGeneratePrDescription",
    "aiPlanOperation",
    "aiReplyRun",
    "aiResolveConflict",
    "aiResolveConflictStream",
    "aiSearchHistory",
    "aiSuggestBranchName",
    "aiSummarizeRange",
    "applyComposedCommits",
    "applyIdentityProfile",
    "applyStash",
    "autoSyncTags",
    "bisectMark",
    "bisectReset",
    "bisectSkip",
    "blameFile",
    "checkAiAvailability",
    "checkForUpdate",
    "checkGitAvailability",
    "checkoutBranch",
    "checkoutCommit",
    "checkoutRemoteBranch",
    "cherrypickAbort",
    "cherrypickCommit",
    "cherrypickContinue",
    "cloneRepo",
    "closeRepo",
    "commit",
    "commitAmend",
    "commitMerge",
    "compareWithHead",
    "compareWithHeadFileDiff",
    "createBranch",
    "createBranchHere",
    "createStash",
    "createTag",
    "deinitSubmodule",
    "deleteAgentAsset",
    "deleteBranch",
    "deleteBranches",
    "deleteProfile",
    "deleteRemoteBranch",
    "deleteRemoteTag",
    "deleteTag",
    "describeLastUndo",
    "discardPartial",
    "discardPaths",
    "discardPathsForce",
    "downloadAndInstallUpdate",
    "dropStash",
    "fetch",
    "fileHistory",
    "forcePush",
    "forceRefreshTag",
    "forgeAddAccount",
    "forgeClearToken",
    "forgeClearTokenForHost",
    "forgeClosePr",
    "forgeCommitStatuses",
    "forgeCreatePr",
    "forgeGetPr",
    "forgeInvalidateViewer",
    "forgeListAccounts",
    "forgeListPrs",
    "forgeListReviewComments",
    "forgeMergePr",
    "forgePrDiff",
    "forgePrFileDiff",
    "forgeRemoveAccount",
    "forgeRepoContext",
    "forgeSetHostDefault",
    "forgeSetRepoAccount",
    "forgeSetToken",
    "forgeSetTokenForHost",
    "generateCommitMessage",
    "getCommitDiff",
    "getCommitFileDiff",
    "getConfig",
    "getConflict",
    "getGraph",
    "getImageDiff",
    "getInteractivePlan",
    "getJobStatus",
    "getMcpStatus",
    "getOpState",
    "getRecentRepos",
    "getRepoHealth",
    "getRepoHooksDisclosure",
    "getSession",
    "getStatus",
    "getUiSettings",
    "getWorkdirFileDiff",
    "gitActivitySubscribe",
    "historyIndexBuild",
    "historyIndexStatus",
    "historySearch",
    "initRepo",
    "initSubmodule",
    "listAgentAssets",
    "listAiAssets",
    "listBranches",
    "listConflicts",
    "listCopyCandidates",
    "listExternalTools",
    "listProfiles",
    "listRemotes",
    "listStaleBranches",
    "listStashes",
    "listSubmodules",
    "listTagSync",
    "listWorktreeContexts",
    "listWorktrees",
    "lockWorktree",
    "logAppend",
    "logExportSession",
    "logRevealDir",
    "logSessionInfo",
    "logsDeleteAll",
    "mergeBranch",
    "metricsReset",
    "metricsSnapshot",
    "onJobStatusChanged",
    "onMcpServerChanged",
    "onRepoChanged",
    "onTagAutoSync",
    "onWindowFocus",
    "openInEditor",
    "openInTerminal",
    "openRepo",
    "openUrl",
    "pickExternalTool",
    "pickFolder",
    "popStash",
    "previewProfile",
    "previewWorktreeCopy",
    "previewWorktreeProfile",
    "pull",
    "push",
    "pushTag",
    "readAgentAsset",
    "readAiAsset",
    "readReflog",
    "rebaseAbort",
    "rebaseBranch",
    "rebaseContinue",
    "rebaseSkip",
    "registerMcpWithClaude",
    "relaunchApp",
    "removeRecentRepo",
    "removeRemote",
    "removeSubmodule",
    "removeWorktree",
    "renameBranch",
    "renameRemote",
    "resetBranch",
    "resolveConflict",
    "resolveConflictText",
    "revealInFileManager",
    "revertAbort",
    "revertCommit",
    "revertContinue",
    "runJobNow",
    "saveAgentAsset",
    "saveProfile",
    "searchCommits",
    "setActiveRepo",
    "setConfig",
    "setMcpAllowWrite",
    "setMcpEnabled",
    "setRemoteUrl",
    "setSession",
    "setUiSettings",
    "signingStatus",
    "stage",
    "stagePartial",
    "startBisect",
    "startInteractiveRebase",
    "streamGraph",
    "syncSubmodule",
    "unlockWorktree",
    "unsetConfig",
    "unstage",
    "unstagePartial",
    "updateSubmodule",
    "verifyCommits",
];

/// True when `name` is an `IpcApi` method — the authoritative `cmd.<name>` key
/// test. `KNOWN_CMDS` is sorted, so this is a binary search, not a scan: it runs
/// once per `ipc.result` record inside `log_append` (§11 keeps that path cheap).
pub(super) fn is_known_cmd(name: &str) -> bool {
    KNOWN_CMDS.binary_search(&name).is_ok()
}

#[cfg(test)]
#[path = "tests_metrics_cmds.rs"]
mod tests_metrics_cmds;
