/**
 * P69 §4 — AI category rows (UI §1.3 #41–#59): Assistance, Runs, Limits, Bulk
 * resolve, AI access (MCP).
 *
 * No `requires` on the Runs/Limits rows: when AI is off the fieldset is DISABLED,
 * not removed (UI §5.4), and `requires` describes absence, not disablement.
 *
 * Three rows deliberately carry no `reset` pair — `Stop a run that goes quiet`,
 * `Stop a run after a fixed time` and `Set a spend limit per run` together with
 * their number rows. Their `0` is a documented mode sentinel (§3.4), so a ↺ would
 * either disable the feature or re-enable it behind the user's back; the switch is
 * already the off-switch.
 */
import type { SettingsIndexEntry } from '../types';
import { resetKey } from './reset';

export const AI_ENTRIES: readonly SettingsIndexEntry[] = [
  {
    id: 'ai.enabled',
    category: 'ai',
    group: 'Assistance',
    label: 'Enable AI features',
    help: 'Master switch for every Claude-powered feature. Nothing leaves your machine until you consent.',
    keywords: 'claude assistant consent',
    control: 'switch',
    reset: resetKey('aiEnabled', 'On'),
  },
  {
    id: 'ai.conflict-resolution',
    category: 'ai',
    group: 'Assistance',
    label: 'Conflict resolution',
    help: 'Whether an AI resolution is proposed for review or written and staged for you.',
    keywords: 'merge resolve autonomy propose',
    control: 'radiogroup',
    reset: resetKey('aiConflictAutonomy', 'Propose & review'),
  },
  {
    id: 'ai.repository-access',
    category: 'ai',
    group: 'Runs',
    label: 'Repository access',
    help: 'What a conflict run may read. Bonsai never lets a run write.',
    keywords: 'sandbox files read-only permissions',
    control: 'segmented',
    reset: resetKey('aiConflictTools', 'Read-only'),
  },
  {
    id: 'ai.stream-output',
    category: 'ai',
    group: 'Runs',
    label: 'Stream AI output',
    help: 'Show log lines in the AI activity dock as they arrive.',
    keywords: 'log dock live progress',
    control: 'switch',
    reset: resetKey('aiStreamLog', 'On'),
  },
  {
    id: 'ai.stream-partial',
    category: 'ai',
    group: 'Runs',
    label: 'Stream partial replies',
    help: 'Ask the CLI for partial message chunks. Off by default.',
    keywords: 'incremental tokens chunks',
    control: 'switch',
    reset: resetKey('aiIncludePartialMessages', 'Off'),
  },
  {
    id: 'ai.idle-timeout-enabled',
    category: 'ai',
    group: 'Limits',
    label: 'Stop a run that goes quiet',
    help: 'End a run that produces no output. The clock pauses while Claude waits for your answer.',
    keywords: 'idle timeout stall hang',
    control: 'switch',
  },
  {
    id: 'ai.idle-timeout-secs',
    category: 'ai',
    group: 'Limits',
    label: 'After',
    help: 'How long a run may stay silent before it is ended.',
    keywords: 'idle seconds timeout quiet',
    control: 'numberSlider',
  },
  {
    id: 'ai.hard-cap-enabled',
    category: 'ai',
    group: 'Limits',
    label: 'Stop a run after a fixed time',
    help: 'Give a run a deadline whatever it is doing.',
    keywords: 'wall clock timeout duration',
    control: 'switch',
  },
  {
    id: 'ai.hard-cap-secs',
    category: 'ai',
    group: 'Limits',
    label: 'Limit',
    help: 'The wall-clock deadline for one run.',
    keywords: 'seconds duration hard cap',
    control: 'numberSlider',
  },
  {
    id: 'ai.max-turns',
    category: 'ai',
    group: 'Limits',
    label: 'Replies per run',
    help: 'How many times Claude may answer inside one run.',
    keywords: 'turns iterations',
    control: 'numberSlider',
    reset: resetKey('aiMaxTurns', '6'),
  },
  {
    id: 'ai.budget-enabled',
    category: 'ai',
    group: 'Limits',
    label: 'Set a spend limit per run',
    help: 'Cap what a single run may cost.',
    keywords: 'budget cost usd dollars money',
    control: 'switch',
  },
  {
    id: 'ai.budget-usd',
    category: 'ai',
    group: 'Limits',
    label: 'Limit',
    help: 'The most one run may spend, in US dollars.',
    keywords: 'budget usd dollars cost spend',
    control: 'numberSlider',
  },
  {
    id: 'ai.bulk-batch-size',
    category: 'ai',
    group: 'Bulk resolve',
    label: 'Batch size',
    help: 'The most text Bonsai puts into one bulk run. Larger merges are split, never truncated.',
    keywords: 'bulk resolve chunk kb',
    control: 'numberSlider',
    reset: resetKey('aiBulkMaxBytes', '400 KB'),
  },
  {
    id: 'ai.mcp-enabled',
    category: 'ai',
    group: 'AI access',
    label: 'Enable MCP server',
    help: 'Run a local server so an external AI client can work with your open repositories.',
    keywords: 'model context protocol port tools',
    control: 'switch',
  },
  {
    id: 'ai.mcp-allow-write',
    category: 'ai',
    group: 'AI access',
    label: 'Allow AI to modify repositories',
    help: 'Adds staging, commit, merge and conflict tools. Restarts the server.',
    keywords: 'write mutation grant',
    control: 'switch',
  },
  {
    id: 'ai.mcp-server-url',
    category: 'ai',
    group: 'AI access',
    label: 'Server URL',
    help: 'The address an MCP client connects to.',
    keywords: 'endpoint address port copy',
    control: 'readonly',
    requires: 'mcpRunning',
  },
  {
    id: 'ai.mcp-token',
    category: 'ai',
    group: 'AI access',
    label: 'Bearer token',
    help: 'The secret an MCP client must send.',
    keywords: 'secret auth credential copy',
    control: 'readonly',
    requires: 'mcpRunning',
  },
  {
    id: 'ai.mcp-register-global',
    category: 'ai',
    group: 'AI access',
    label: 'Register with Claude Code · Globally',
    help: 'Add Bonsai to your user-level Claude Code MCP config.',
    keywords: 'install claude code user scope',
    control: 'button',
    requires: 'mcpRunning',
  },
  {
    id: 'ai.mcp-register-repo',
    category: 'ai',
    group: 'AI access',
    label: 'Register with Claude Code · This repository',
    help: 'Add Bonsai to the open repository’s Claude Code MCP config.',
    keywords: 'install claude code local scope',
    control: 'button',
    requires: 'mcpRunning',
  },
];
