/** P69 §4 — Commit graph category rows (UI §1.3 #10–#21). */
import type { SettingsIndexEntry } from '../types';
import { resetField } from './reset';

export const GRAPH_ENTRIES: readonly SettingsIndexEntry[] = [
  {
    id: 'graph.node-size',
    category: 'graph',
    group: 'Geometry',
    label: 'Commit node size',
    help: 'Radius of the dot on each commit.',
    keywords: 'dot radius avatar graph',
    control: 'numberSlider',
    reset: resetField('graph', 'avatarRadius', '10'),
  },
  {
    id: 'graph.row-height',
    category: 'graph',
    group: 'Geometry',
    label: 'Row height',
    help: 'Vertical space per commit row.',
    keywords: 'density spacing graph rows',
    control: 'numberSlider',
    reset: resetField('graph', 'rowHeight', '32'),
  },
  {
    id: 'graph.lane-width',
    category: 'graph',
    group: 'Geometry',
    label: 'Lane width',
    help: 'Horizontal space between branch lanes.',
    keywords: 'column spacing branches graph',
    control: 'numberSlider',
    reset: resetField('graph', 'laneWidth', '16'),
  },
  {
    id: 'graph.compact-rows',
    category: 'graph',
    group: 'Geometry',
    label: 'Compact rows',
    help: 'Tighten row geometry to fit more commits on screen.',
    keywords: 'density graph small',
    control: 'switch',
    reset: resetField('graph', 'compact', 'Off'),
  },
  {
    id: 'graph.short-sha',
    category: 'graph',
    group: 'Row details',
    label: 'Short SHA',
    help: 'Show the abbreviated commit id in each row.',
    keywords: 'hash oid abbreviated id',
    control: 'switch',
    reset: resetField('graph', 'showSha', 'On'),
  },
  {
    id: 'graph.author-name',
    category: 'graph',
    group: 'Row details',
    label: 'Author name',
    help: 'Show who wrote each commit.',
    keywords: 'person who wrote',
    control: 'switch',
    reset: resetField('graph', 'showAuthor', 'Off'),
  },
  {
    id: 'graph.date',
    category: 'graph',
    group: 'Row details',
    label: 'Date',
    help: 'Show the date column.',
    keywords: 'time when timestamp',
    control: 'switch',
    reset: resetField('graph', 'showDate', 'On'),
  },
  {
    id: 'graph.date-basis',
    category: 'graph',
    group: 'Row details',
    label: 'Date basis',
    help: 'Whether dates come from the author or the committer.',
    keywords: 'author committer timestamp',
    control: 'segmented',
    reset: resetField('graph', 'dateBasis', 'Author'),
  },
  {
    id: 'graph.ahead-behind',
    category: 'graph',
    group: 'Badges',
    label: 'Ahead/behind on branches',
    help: 'Show how far each branch has diverged from its upstream.',
    keywords: 'divergence upstream counts',
    control: 'switch',
    reset: resetField('graph', 'showAheadBehind', 'On'),
  },
  {
    id: 'graph.signature-badge',
    category: 'graph',
    group: 'Badges',
    label: 'Signature badge',
    help: 'Mark commits carrying a verified signature.',
    keywords: 'gpg ssh signed verified',
    control: 'switch',
    reset: resetField('graph', 'showSignatureBadge', 'On'),
  },
  {
    id: 'graph.pr-badges',
    category: 'graph',
    group: 'Badges',
    label: 'Show PR badges',
    help: 'Mark commits that belong to an open pull request.',
    keywords: 'pull request forge github azure',
    control: 'switch',
    reset: resetField('graph', 'showPrBadge', 'Off'),
  },
  {
    id: 'graph.ci-status',
    category: 'graph',
    group: 'Badges',
    label: 'Show CI status',
    help: 'Show the latest pipeline result on each commit.',
    keywords: 'checks pipeline build forge',
    control: 'switch',
    reset: resetField('graph', 'showCiStatus', 'Off'),
  },
];
