//! Mutation tools (§7.3) — registered into the router only when write access
//! is granted (the standalone server's `--allow-write` CLI flag, or the app's
//! `mcpAllowWrite` setting for the embedded server; the per-tool descriptions
//! therefore say "requires write access" rather than naming one of the two).
//! Split out of `server.rs`; the `#[tool_router(router = write_router)]` macro
//! generates `BonsaiServer::write_router()`, consumed by the constructor in the
//! module root.
//!
//! Several tools apply an MCP-only precondition from [`write_guards`] before
//! calling the shared `bonsai_core` primitive (audit 2026-09-11): the primitives
//! document trust in the UI as their caller, and a model is not the UI.

use super::*;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::{tool, tool_router};

// ---------------------------------------------------------------------------
// Mutation tools (§7.3). Registered into `tool_router` only when write access
// is granted (see `with_source`); when off, this router is never merged so the
// tools do not appear in `tools/list`. `Self::write_router()` is generated by
// the macro and merged with the stash router by `write_mutation_router()`.
// ---------------------------------------------------------------------------

#[tool_router(router = write_router, vis = "pub(crate)")]
impl BonsaiServer {
    /// Atomically stage a batch of repo-relative paths (worktree untouched).
    ///
    /// Stage the whole batch in one call rather than one path per call - it is atomic,
    /// so either every path is staged or none is. Paths are repo-relative with forward
    /// slashes and are ENFORCED to come from `bonsai_get_status`: a path absent from
    /// its staged / unstaged / untracked / conflicted lists fails the whole batch with
    /// `invalidName` and stages nothing, so an ignored file (`.env`) or an unchanged
    /// file cannot be staged here. A path status reports as DELETED stages that
    /// deletion; a path status reports as CONFLICTED is accepted only once the file
    /// no longer contains conflict markers (staging it is `markResolved` by another
    /// name), else `unresolvedConflicts`. Requires write access. Does not commit;
    /// follow with `bonsai_commit`.
    #[tool]
    async fn bonsai_stage(&self, Parameters(args): Parameters<PathsArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                // audit 2026-09-11 MEDIUM: `stage_paths` has `git add -f`
                // semantics and trusts the UI's "paths come from StatusSnapshot"
                // precondition. A model is not the UI, so enforce it here (same
                // worker thread + open-repo moment as the stage itself).
                write_guards::ensure_paths_in_status(wd, &args.paths)?;
                bonsai_core::git::stage::stage_paths(wd, &args.paths)
            })
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Unstage a batch of repo-relative paths (never touches the worktree).
    ///
    /// The exact inverse of `bonsai_stage` and equally atomic: it moves paths out of
    /// the index and leaves the file on disk untouched, so no edit can be lost this
    /// way. Requires write access. This is not a way to discard changes - there is
    /// no discard tool on this server.
    #[tool]
    async fn bonsai_unstage(&self, Parameters(args): Parameters<PathsArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::stage::unstage_paths(wd, &args.paths))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a commit from the staged index. Errors clearly on empty message,
    /// missing git identity, or nothing-to-commit (preserved `kind`).
    ///
    /// Commits the index only - unstaged edits are left behind, so stage first.
    /// Returns the new commit's oid, summary, and branch, plus a `hookWarning` when a
    /// repository hook emitted output. Refusals arrive as typed kinds:
    /// `emptyMessage`, `configMissing` (no user.name/user.email), `nothingToCommit`,
    /// or `hookRejected` when a hook vetoed it. Requires write access. Cannot
    /// amend; there is no amend tool here. Use `bonsai_commit_merge` to conclude a
    /// merge. A repository with runnable `pre-commit` / `commit-msg` / `post-commit`
    /// hooks may refuse the commit outright with `hooksNotPermitted` (the hooks are
    /// repository-authored code and this server cannot disclose them to the user);
    /// no hook runs and nothing changes, and the error says how the user can permit
    /// or disable them - do not retry it unchanged.
    #[tool]
    async fn bonsai_commit(&self, Parameters(args): Parameters<MessageArgs>) -> CallToolResult {
        // audit 2026-09-11 LOW: hooks run with `skip_hooks=false` below, but the
        // one-time disclosure lives in the app's frontend — unreachable for a
        // standalone stdio server. Probe (blocking) only when that applies.
        let guard_hooks = self.hooks_need_disclosure();
        match self
            .run_blocking(move |wd| {
                if guard_hooks {
                    write_guards::ensure_commit_hooks_disclosed(wd)?;
                }
                bonsai_core::git::commit::create_commit(wd, &args.message, None, false)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Resolve a conflicted file by writing AI-authored final content to the
    /// worktree and staging it (the primary AI resolution path).
    ///
    /// Writes `content` verbatim as the whole file, then stages it - the merged text
    /// must therefore be complete and carry NO conflict markers. Content that still
    /// has a `<<<<<<<`, `=======`, or `>>>>>>>` line is REFUSED with
    /// `unresolvedConflicts` and nothing is written or staged. Read the sides with
    /// `bonsai_get_conflict` first, and do not use this for a binary, too-large, or
    /// missing-side conflict. Requires write access. Errors if the path is not
    /// currently conflicted. Resolving every path does not conclude the operation;
    /// finish with `bonsai_commit_merge` or `bonsai_rebase_continue`.
    #[tool]
    async fn bonsai_resolve_conflict_text(
        &self,
        Parameters(args): Parameters<ResolveConflictTextArgs>,
    ) -> CallToolResult {
        // audit 2026-09-11 LOW: the core primitive documents "Trust the caller"
        // and relies on the frontend's `hasUnresolvedMarkers` Save gate, which
        // does not exist over MCP. Pure text check, before any fs write.
        if let Err(e) = write_guards::ensure_no_conflict_markers(&args.path, &args.content) {
            return err_result(e);
        }
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::conflict::resolve_conflict_text(wd, &args.path, &args.content)
            })
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Resolve a conflicted file via take-ours / take-theirs / mark-resolved.
    ///
    /// The whole-side alternative to `bonsai_resolve_conflict_text`: use it when one
    /// side wins outright, or for binary and delete/add conflicts where no merged text
    /// exists. `resolution` accepts `ours`, `theirs`, or `markResolved` - an
    /// unrecognized value fails with `invalidName`, and `markResolved` stages the file
    /// as it currently stands on disk without changing it. Because `markResolved`
    /// stages the file unchanged, it is REFUSED with `unresolvedConflicts` when that
    /// file still contains conflict-marker lines (or is too large to check).
    /// Requires write access. Errors if the path is not currently conflicted.
    #[tool]
    async fn bonsai_resolve_conflict(
        &self,
        Parameters(args): Parameters<ResolveConflictArgs>,
    ) -> CallToolResult {
        let resolution = match parse_resolution(&args.resolution) {
            Ok(r) => r,
            Err(e) => return err_result(e),
        };
        // audit 2026-09-11 LOW: `markResolved` stages the worktree file as-is
        // ("the user is trusted"), so over MCP verify it holds no markers. Same
        // closure as the mutation — no extra spawn, no widened race.
        let check_markers = matches!(
            resolution,
            bonsai_core::git::conflict::ConflictResolution::MarkResolved
        );
        match self
            .run_blocking(move |wd| {
                if check_markers {
                    write_guards::ensure_worktree_has_no_markers(wd, &args.path)?;
                }
                bonsai_core::git::conflict::resolve_conflict(wd, &args.path, resolution)
            })
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Merge a branch into the current branch (FF / clean-merge / conflicts are
    /// distinguished in the typed outcome; autostash handled; never force).
    ///
    /// Read the outcome tag before doing anything else: `upToDate`, `fastForwarded`,
    /// `merged`, `conflicts` (paused, worktree holds markers), or `stashPopConflicts`
    /// (the merge landed but restoring the autostash conflicted). Only `conflicts`
    /// starts the resolution loop - resolve each path, then `bonsai_commit_merge`, or
    /// `bonsai_abort_merge` to unwind. Requires write access. Never forces and
    /// never discards work; a dirty worktree is autostashed and restored. Fails with
    /// `operationInProgress` if a merge or rebase is already in flight. A merge that
    /// is not a fast-forward auto-commits, which runs the repository's `commit-msg`
    /// hook; where this server may not run hooks that is refused up front with
    /// `hooksNotPermitted`, before anything is merged, committed or stashed.
    #[tool]
    async fn bonsai_merge_branch(&self, Parameters(args): Parameters<NameArgs>) -> CallToolResult {
        // review 2026-09-11 MUST-FIX: the clean auto-merge runs `commit-msg`
        // (merge/branch.rs -> finalize.rs), so this path needs the same
        // undisclosed-hook consent as `bonsai_commit`. It cannot use the
        // pre-call guard (that would refuse FF / up-to-date merges, which run
        // nothing) — core consults the gate itself, at the one point that knows
        // the merge is a real merge and before any mutation.
        let gate = write_guards::merge_hooks_gate(self.hooks_need_disclosure());
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::merge::merge_branch_gated(wd, &args.name, gate)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Finalize a paused merge (refuses on `unresolvedConflicts`).
    ///
    /// The concluding step after `bonsai_merge_branch` returned `conflicts` and every
    /// path has been resolved; it writes the merge commit and clears the operation.
    /// Refuses with `unresolvedConflicts` while any path is still conflicted - check
    /// with `bonsai_list_conflicts` first - and with `noOperationInProgress` when no
    /// merge is paused. Returns the new commit's oid, summary, and branch. Requires
    /// write access. Not for ordinary commits; use `bonsai_commit`. Like
    /// `bonsai_commit`, a repository with runnable commit hooks may refuse outright
    /// with `hooksNotPermitted`, in which case nothing was committed.
    #[tool]
    async fn bonsai_commit_merge(
        &self,
        Parameters(args): Parameters<MessageArgs>,
    ) -> CallToolResult {
        // audit 2026-09-11 LOW: same undisclosed-hook path as `bonsai_commit`
        // (merge/finalize.rs runs pre-commit BLOCKING + post-commit).
        let guard_hooks = self.hooks_need_disclosure();
        match self
            .run_blocking(move |wd| {
                if guard_hooks {
                    write_guards::ensure_commit_hooks_disclosed(wd)?;
                }
                bonsai_core::git::merge::commit_merge(wd, &args.message, None, false)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Abort an in-progress merge, resetting the worktree and index to the
    /// pre-merge state.
    ///
    /// Destructive: conflict-resolution edits made during the merge are discarded and
    /// cannot be recovered - prefer resolving and `bonsai_commit_merge` when the work
    /// is worth keeping. Requires write access. Confirm a merge is actually paused
    /// with `bonsai_get_op_state` first; aborting when none is in flight fails with
    /// `noOperationInProgress`. Does not touch a rebase - use `bonsai_rebase_abort`.
    #[tool]
    async fn bonsai_abort_merge(&self) -> CallToolResult {
        match self.run_blocking(bonsai_core::git::merge::abort_merge).await {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Rebase the current branch onto another ref (typed FF/rebased/conflicts
    /// with step counters).
    ///
    /// Branch on the outcome tag: `upToDate`, `fastForwarded`, `rebased`, or
    /// `conflicts` - the last pauses mid-rebase with markers in the worktree and step
    /// counters showing progress. From a pause, resolve and `bonsai_rebase_continue`,
    /// drop the current commit with `bonsai_rebase_skip`, or unwind everything with
    /// `bonsai_rebase_abort`. Requires write access. Rewrites the current branch's
    /// history, so commit oids change. Fails with `operationInProgress` if another
    /// operation is already in flight.
    #[tool]
    async fn bonsai_rebase_branch(&self, Parameters(args): Parameters<OntoArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::rebase::rebase_branch(wd, &args.onto))
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Resume a paused rebase after resolving the current step's conflicts.
    ///
    /// Returns the same typed outcome as `bonsai_rebase_branch`, so a multi-commit
    /// rebase can pause again on the next step - loop until the tag is no longer
    /// `conflicts` rather than assuming one continue finishes it. Refuses with
    /// `unresolvedConflicts` while any path is still conflicted, and with
    /// `noOperationInProgress` when no rebase is paused. Requires write access.
    #[tool]
    async fn bonsai_rebase_continue(&self) -> CallToolResult {
        match self
            .run_blocking(bonsai_core::git::rebase::rebase_continue)
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Skip the current step of a paused rebase.
    ///
    /// Discards the commit currently being applied and moves to the next step - that
    /// commit's changes are dropped from the rebased branch and are not recoverable
    /// from the new history. Use it only when the commit is genuinely redundant;
    /// otherwise resolve and continue. Returns the same typed outcome as
    /// `bonsai_rebase_continue`, so the rebase may pause again. Requires
    /// write access.
    #[tool]
    async fn bonsai_rebase_skip(&self) -> CallToolResult {
        match self
            .run_blocking(bonsai_core::git::rebase::rebase_skip)
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Abort an in-progress rebase, returning the branch to its pre-rebase tip.
    ///
    /// Destructive: commits already replayed by completed steps and any
    /// conflict-resolution edits in the worktree are discarded. Requires
    /// write access. Confirm a rebase is actually paused with
    /// `bonsai_get_op_state`; aborting when none is in flight fails with
    /// `noOperationInProgress`. Does not touch a merge - use `bonsai_abort_merge`.
    #[tool]
    async fn bonsai_rebase_abort(&self) -> CallToolResult {
        match self
            .run_blocking(bonsai_core::git::rebase::rebase_abort)
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a branch at HEAD (no checkout).
    ///
    /// Leaves HEAD, the index, and the worktree exactly as they are, so it is safe
    /// with a dirty tree - a separate `bonsai_checkout_branch` switches to it. Fails
    /// with `branchExists` if the name is taken and `invalidName` if it is not a legal
    /// ref. Requires write access. To branch from somewhere other than HEAD, use
    /// `bonsai_create_branch_here`.
    #[tool]
    async fn bonsai_create_branch(&self, Parameters(args): Parameters<NameArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::branches::create_branch(wd, &args.name))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a branch at a specific commit and check it out (autostash across
    /// the checkout).
    ///
    /// Unlike `bonsai_create_branch` this DOES move HEAD, so a dirty worktree is
    /// autostashed and restored around the switch; the result reports whether a stash
    /// was taken and how restoring it went. Requires a full 40-char hex oid. Fails
    /// with `branchExists`, `invalidName`, or `checkoutConflict`. Requires
    /// write access.
    #[tool]
    async fn bonsai_create_branch_here(
        &self,
        Parameters(args): Parameters<CreateBranchHereArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::branches::create_branch_here(wd, &args.name, &args.oid)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Safely checkout a branch - never force; `checkoutConflict` surfaces
    /// instead of clobbering the worktree.
    ///
    /// Refuses rather than overwriting: local edits that would be lost produce
    /// `checkoutConflict` and nothing changes, so no work can be destroyed through
    /// this tool. Also fails with `branchNotFound`, and with
    /// `branchCheckedOutElsewhere` when another worktree already holds the branch.
    /// Does not autostash - commit or stash first, or use
    /// `bonsai_create_branch_here`, which does. Requires write access.
    #[tool]
    async fn bonsai_checkout_branch(
        &self,
        Parameters(args): Parameters<NameArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::branches::checkout_branch(wd, &args.name))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Delete a local branch. Refuses with `unmergedBranch` when the branch
    /// holds commits that would be lost; there is no force variant.
    ///
    /// Because there is no force path, an unmerged branch simply cannot be deleted
    /// through this server - that is deliberate. Also fails with `branchNotFound`, and
    /// refuses to delete the branch currently checked out. Deletes the local ref only:
    /// the remote branch and its remote-tracking ref are untouched. Requires
    /// write access.
    #[tool]
    async fn bonsai_delete_branch(&self, Parameters(args): Parameters<NameArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::branches::delete_branch(wd, &args.name))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }
}
