//! Mutation tools (§7.3) — registered into the router only under
//! `--allow-write`. Split out of `server.rs`; the `#[tool_router(router =
//! write_router)]` macro generates `BonsaiServer::write_router()`, consumed by
//! the constructor in the module root. Behavior unchanged.

use super::*;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::{tool, tool_router};

// ---------------------------------------------------------------------------
// Mutation tools (§7.3). Registered into `tool_router` only when `--allow-write`
// (see `new()`); when off, this router is never merged so the tools do not
// appear in `tools/list`. `Self::write_router()` is generated by the macro.
// ---------------------------------------------------------------------------

#[tool_router(router = write_router, vis = "pub(crate)")]
impl BonsaiServer {
    /// Atomically stage a batch of repo-relative paths (worktree untouched).
    #[tool]
    async fn bonsai_stage(&self, Parameters(args): Parameters<PathsArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::stage::stage_paths(wd, &args.paths))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Unstage a batch of repo-relative paths (never touches the worktree).
    #[tool]
    async fn bonsai_unstage(&self, Parameters(args): Parameters<PathsArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::stage::unstage_paths(wd, &args.paths))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a commit from the staged index. Errors clearly on empty message,
    /// missing git identity, or nothing-to-commit (preserved `kind`).
    #[tool]
    async fn bonsai_commit(&self, Parameters(args): Parameters<MessageArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::commit::create_commit(wd, &args.message, None, false))
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Resolve a conflicted file by writing AI-authored final content to the
    /// worktree and staging it (the primary AI resolution path).
    #[tool]
    async fn bonsai_resolve_conflict_text(
        &self,
        Parameters(args): Parameters<ResolveConflictTextArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::conflict::resolve_conflict_text(wd, &args.path, &args.content)
            })
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Resolve a conflicted file via take-ours / take-theirs / mark-resolved.
    #[tool]
    async fn bonsai_resolve_conflict(
        &self,
        Parameters(args): Parameters<ResolveConflictArgs>,
    ) -> CallToolResult {
        let resolution = match parse_resolution(&args.resolution) {
            Ok(r) => r,
            Err(e) => return err_result(e),
        };
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::conflict::resolve_conflict(wd, &args.path, resolution)
            })
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Merge a branch into the current branch (FF / clean-merge / conflicts are
    /// distinguished in the typed outcome; autostash handled; never force).
    #[tool]
    async fn bonsai_merge_branch(&self, Parameters(args): Parameters<NameArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::merge::merge_branch(wd, &args.name, false))
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Finalize a paused merge (refuses on `unresolvedConflicts`).
    #[tool]
    async fn bonsai_commit_merge(
        &self,
        Parameters(args): Parameters<MessageArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::merge::commit_merge(wd, &args.message, None, false))
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Abort an in-progress merge (worktree-destructive; gated by `--allow-write`).
    #[tool]
    async fn bonsai_abort_merge(&self) -> CallToolResult {
        match self.run_blocking(bonsai_core::git::merge::abort_merge).await {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Rebase the current branch onto another ref (typed FF/rebased/conflicts
    /// with step counters).
    #[tool]
    async fn bonsai_rebase_branch(&self, Parameters(args): Parameters<OntoArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::rebase::rebase_branch(wd, &args.onto))
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Resume a paused rebase after resolving the current step's conflicts.
    #[tool]
    async fn bonsai_rebase_continue(&self) -> CallToolResult {
        match self
            .run_blocking(bonsai_core::git::rebase::rebase_continue)
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Skip the current step of a paused rebase.
    #[tool]
    async fn bonsai_rebase_skip(&self) -> CallToolResult {
        match self
            .run_blocking(bonsai_core::git::rebase::rebase_skip)
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Abort an in-progress rebase (worktree-destructive; gated).
    #[tool]
    async fn bonsai_rebase_abort(&self) -> CallToolResult {
        match self
            .run_blocking(bonsai_core::git::rebase::rebase_abort)
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a branch at HEAD (no checkout).
    #[tool]
    async fn bonsai_create_branch(&self, Parameters(args): Parameters<NameArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::branches::create_branch(wd, &args.name))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a branch at a specific commit (autostash across the checkout).
    #[tool]
    async fn bonsai_create_branch_here(
        &self,
        Parameters(args): Parameters<CreateBranchHereArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::branches::create_branch_here(wd, &args.name, &args.oid)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Safely checkout a branch — never force; `checkoutConflict` surfaces
    /// instead of clobbering the worktree.
    #[tool]
    async fn bonsai_checkout_branch(
        &self,
        Parameters(args): Parameters<NameArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::branches::checkout_branch(wd, &args.name))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Delete a branch — blocks unmerged deletion (`unmergedBranch`); no force.
    #[tool]
    async fn bonsai_delete_branch(&self, Parameters(args): Parameters<NameArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::branches::delete_branch(wd, &args.name))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a stash. `created=false` means nothing to stash (not an error).
    #[tool]
    async fn bonsai_create_stash(
        &self,
        Parameters(args): Parameters<CreateStashArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                let scope = if args.include_untracked {
                    bonsai_core::git::stash::StashScope::AllWithUntracked
                } else {
                    bonsai_core::git::stash::StashScope::All
                };
                bonsai_core::git::stash::create_stash(wd, args.message.as_deref(), scope)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Apply a stash without dropping it; conflicts reported as typed paths.
    ///
    /// If the stash contains Windows-reserved paths (e.g. `NUL`) that cannot be
    /// checked out, the first attempt (`skipReserved` false/omitted) applies
    /// nothing and returns a `reservedPaths` outcome listing them; retry with
    /// `skipReserved: true` to apply the rest, yielding `appliedSkippingReserved`.
    #[tool]
    async fn bonsai_apply_stash(
        &self,
        Parameters(args): Parameters<StashApplyArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::stash::apply_stash(wd, args.index, args.skip_reserved, None)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Apply a stash and drop it on clean success only.
    ///
    /// If the stash contains Windows-reserved paths (e.g. `NUL`) that cannot be
    /// checked out, the first attempt (`skipReserved` false/omitted) applies
    /// nothing and returns a `reservedPaths` outcome listing them; retry with
    /// `skipReserved: true` to apply the rest (`appliedSkippingReserved`). When
    /// any path is skipped the stash is KEPT (not dropped) so nothing is lost.
    #[tool]
    async fn bonsai_pop_stash(
        &self,
        Parameters(args): Parameters<StashApplyArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::stash::pop_stash(wd, args.index, args.skip_reserved, None)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Permanently drop a stash (gated by `--allow-write`).
    #[tool]
    async fn bonsai_drop_stash(
        &self,
        Parameters(args): Parameters<StashIndexArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::stash::drop_stash(wd, args.index, None))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }
}
