//! Mutation tools (§7.3) — registered into the router only under
//! `--allow-write`. Split out of `server.rs`; the `#[tool_router(router =
//! write_router)]` macro generates `BonsaiServer::write_router()`, consumed by
//! the constructor in the module root. Behavior unchanged.

use super::*;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::{tool, tool_router};

// ---------------------------------------------------------------------------
// Mutation tools (§7.3). Registered into `tool_router` only when `--allow-write`
// (see `new()`); when off, this router is never merged so the tools do not
// appear in `tools/list`. `Self::write_router()` is generated by the macro.
// ---------------------------------------------------------------------------

#[tool_router(router = write_router, vis = "pub(crate)")]
impl BonsaiServer {
    /// Atomically stage a batch of repo-relative paths (worktree untouched).
    ///
    /// Stage the whole batch in one call rather than one path per call - it is atomic,
    /// so either every path is staged or none is. Paths are repo-relative with forward
    /// slashes and must come from `bonsai_get_status`; a path that does not exist fails
    /// the batch. Requires `--allow-write`. Does not commit; follow with
    /// `bonsai_commit`.
    #[tool]
    async fn bonsai_stage(&self, Parameters(args): Parameters<PathsArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::stage::stage_paths(wd, &args.paths))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Unstage a batch of repo-relative paths (never touches the worktree).
    ///
    /// The exact inverse of `bonsai_stage` and equally atomic: it moves paths out of
    /// the index and leaves the file on disk untouched, so no edit can be lost this
    /// way. Requires `--allow-write`. This is not a way to discard changes - there is
    /// no discard tool on this server.
    #[tool]
    async fn bonsai_unstage(&self, Parameters(args): Parameters<PathsArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::stage::unstage_paths(wd, &args.paths))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a commit from the staged index. Errors clearly on empty message,
    /// missing git identity, or nothing-to-commit (preserved `kind`).
    ///
    /// Commits the index only - unstaged edits are left behind, so stage first.
    /// Returns the new commit's oid, summary, and branch, plus a `hookWarning` when a
    /// repository hook emitted output. Refusals arrive as typed kinds:
    /// `emptyMessage`, `configMissing` (no user.name/user.email), `nothingToCommit`,
    /// or `hookRejected` when a hook vetoed it. Requires `--allow-write`. Cannot
    /// amend; there is no amend tool here. Use `bonsai_commit_merge` to conclude a
    /// merge.
    #[tool]
    async fn bonsai_commit(&self, Parameters(args): Parameters<MessageArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::commit::create_commit(wd, &args.message, None, false))
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Resolve a conflicted file by writing AI-authored final content to the
    /// worktree and staging it (the primary AI resolution path).
    ///
    /// Writes `content` verbatim as the whole file, then stages it - the merged text
    /// must therefore be complete and carry NO conflict markers, since nothing strips
    /// them. Read the sides with `bonsai_get_conflict` first, and do not use this for
    /// a binary, too-large, or missing-side conflict. Requires `--allow-write`. Errors
    /// if the path is not currently conflicted. Resolving every path does not conclude
    /// the operation; finish with `bonsai_commit_merge` or `bonsai_rebase_continue`.
    #[tool]
    async fn bonsai_resolve_conflict_text(
        &self,
        Parameters(args): Parameters<ResolveConflictTextArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::conflict::resolve_conflict_text(wd, &args.path, &args.content)
            })
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Resolve a conflicted file via take-ours / take-theirs / mark-resolved.
    ///
    /// The whole-side alternative to `bonsai_resolve_conflict_text`: use it when one
    /// side wins outright, or for binary and delete/add conflicts where no merged text
    /// exists. `resolution` accepts `ours`, `theirs`, or `markResolved` - an
    /// unrecognized value fails with `invalidName`, and `markResolved` stages the file
    /// as it currently stands on disk without changing it. Requires `--allow-write`.
    /// Errors if the path is not currently conflicted.
    #[tool]
    async fn bonsai_resolve_conflict(
        &self,
        Parameters(args): Parameters<ResolveConflictArgs>,
    ) -> CallToolResult {
        let resolution = match parse_resolution(&args.resolution) {
            Ok(r) => r,
            Err(e) => return err_result(e),
        };
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::conflict::resolve_conflict(wd, &args.path, resolution)
            })
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Merge a branch into the current branch (FF / clean-merge / conflicts are
    /// distinguished in the typed outcome; autostash handled; never force).
    ///
    /// Read the outcome tag before doing anything else: `upToDate`, `fastForwarded`,
    /// `merged`, `conflicts` (paused, worktree holds markers), or `stashPopConflicts`
    /// (the merge landed but restoring the autostash conflicted). Only `conflicts`
    /// starts the resolution loop - resolve each path, then `bonsai_commit_merge`, or
    /// `bonsai_abort_merge` to unwind. Requires `--allow-write`. Never forces and
    /// never discards work; a dirty worktree is autostashed and restored. Fails with
    /// `operationInProgress` if a merge or rebase is already in flight.
    #[tool]
    async fn bonsai_merge_branch(&self, Parameters(args): Parameters<NameArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::merge::merge_branch(wd, &args.name, false))
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Finalize a paused merge (refuses on `unresolvedConflicts`).
    ///
    /// The concluding step after `bonsai_merge_branch` returned `conflicts` and every
    /// path has been resolved; it writes the merge commit and clears the operation.
    /// Refuses with `unresolvedConflicts` while any path is still conflicted - check
    /// with `bonsai_list_conflicts` first - and with `noOperationInProgress` when no
    /// merge is paused. Returns the new commit's oid, summary, and branch. Requires
    /// `--allow-write`. Not for ordinary commits; use `bonsai_commit`.
    #[tool]
    async fn bonsai_commit_merge(
        &self,
        Parameters(args): Parameters<MessageArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::merge::commit_merge(wd, &args.message, None, false))
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Abort an in-progress merge, resetting the worktree and index to the
    /// pre-merge state.
    ///
    /// Destructive: conflict-resolution edits made during the merge are discarded and
    /// cannot be recovered - prefer resolving and `bonsai_commit_merge` when the work
    /// is worth keeping. Requires `--allow-write`. Confirm a merge is actually paused
    /// with `bonsai_get_op_state` first; aborting when none is in flight fails with
    /// `noOperationInProgress`. Does not touch a rebase - use `bonsai_rebase_abort`.
    #[tool]
    async fn bonsai_abort_merge(&self) -> CallToolResult {
        match self.run_blocking(bonsai_core::git::merge::abort_merge).await {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Rebase the current branch onto another ref (typed FF/rebased/conflicts
    /// with step counters).
    ///
    /// Branch on the outcome tag: `upToDate`, `fastForwarded`, `rebased`, or
    /// `conflicts` - the last pauses mid-rebase with markers in the worktree and step
    /// counters showing progress. From a pause, resolve and `bonsai_rebase_continue`,
    /// drop the current commit with `bonsai_rebase_skip`, or unwind everything with
    /// `bonsai_rebase_abort`. Requires `--allow-write`. Rewrites the current branch's
    /// history, so commit oids change. Fails with `operationInProgress` if another
    /// operation is already in flight.
    #[tool]
    async fn bonsai_rebase_branch(&self, Parameters(args): Parameters<OntoArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::rebase::rebase_branch(wd, &args.onto))
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Resume a paused rebase after resolving the current step's conflicts.
    ///
    /// Returns the same typed outcome as `bonsai_rebase_branch`, so a multi-commit
    /// rebase can pause again on the next step - loop until the tag is no longer
    /// `conflicts` rather than assuming one continue finishes it. Refuses with
    /// `unresolvedConflicts` while any path is still conflicted, and with
    /// `noOperationInProgress` when no rebase is paused. Requires `--allow-write`.
    #[tool]
    async fn bonsai_rebase_continue(&self) -> CallToolResult {
        match self
            .run_blocking(bonsai_core::git::rebase::rebase_continue)
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Skip the current step of a paused rebase.
    ///
    /// Discards the commit currently being applied and moves to the next step - that
    /// commit's changes are dropped from the rebased branch and are not recoverable
    /// from the new history. Use it only when the commit is genuinely redundant;
    /// otherwise resolve and continue. Returns the same typed outcome as
    /// `bonsai_rebase_continue`, so the rebase may pause again. Requires
    /// `--allow-write`.
    #[tool]
    async fn bonsai_rebase_skip(&self) -> CallToolResult {
        match self
            .run_blocking(bonsai_core::git::rebase::rebase_skip)
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Abort an in-progress rebase, returning the branch to its pre-rebase tip.
    ///
    /// Destructive: commits already replayed by completed steps and any
    /// conflict-resolution edits in the worktree are discarded. Requires
    /// `--allow-write`. Confirm a rebase is actually paused with
    /// `bonsai_get_op_state`; aborting when none is in flight fails with
    /// `noOperationInProgress`. Does not touch a merge - use `bonsai_abort_merge`.
    #[tool]
    async fn bonsai_rebase_abort(&self) -> CallToolResult {
        match self
            .run_blocking(bonsai_core::git::rebase::rebase_abort)
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a branch at HEAD (no checkout).
    ///
    /// Leaves HEAD, the index, and the worktree exactly as they are, so it is safe
    /// with a dirty tree - a separate `bonsai_checkout_branch` switches to it. Fails
    /// with `branchExists` if the name is taken and `invalidName` if it is not a legal
    /// ref. Requires `--allow-write`. To branch from somewhere other than HEAD, use
    /// `bonsai_create_branch_here`.
    #[tool]
    async fn bonsai_create_branch(&self, Parameters(args): Parameters<NameArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::branches::create_branch(wd, &args.name))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a branch at a specific commit and check it out (autostash across
    /// the checkout).
    ///
    /// Unlike `bonsai_create_branch` this DOES move HEAD, so a dirty worktree is
    /// autostashed and restored around the switch; the result reports whether a stash
    /// was taken and how restoring it went. Requires a full 40-char hex oid. Fails
    /// with `branchExists`, `invalidName`, or `checkoutConflict`. Requires
    /// `--allow-write`.
    #[tool]
    async fn bonsai_create_branch_here(
        &self,
        Parameters(args): Parameters<CreateBranchHereArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::branches::create_branch_here(wd, &args.name, &args.oid)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Safely checkout a branch - never force; `checkoutConflict` surfaces
    /// instead of clobbering the worktree.
    ///
    /// Refuses rather than overwriting: local edits that would be lost produce
    /// `checkoutConflict` and nothing changes, so no work can be destroyed through
    /// this tool. Also fails with `branchNotFound`, and with
    /// `branchCheckedOutElsewhere` when another worktree already holds the branch.
    /// Does not autostash - commit or stash first, or use
    /// `bonsai_create_branch_here`, which does. Requires `--allow-write`.
    #[tool]
    async fn bonsai_checkout_branch(
        &self,
        Parameters(args): Parameters<NameArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::branches::checkout_branch(wd, &args.name))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Delete a local branch. Refuses with `unmergedBranch` when the branch
    /// holds commits that would be lost; there is no force variant.
    ///
    /// Because there is no force path, an unmerged branch simply cannot be deleted
    /// through this server - that is deliberate. Also fails with `branchNotFound`, and
    /// refuses to delete the branch currently checked out. Deletes the local ref only:
    /// the remote branch and its remote-tracking ref are untouched. Requires
    /// `--allow-write`.
    #[tool]
    async fn bonsai_delete_branch(&self, Parameters(args): Parameters<NameArgs>) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::branches::delete_branch(wd, &args.name))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }

    /// Create a stash. `created=false` means nothing to stash (not an error).
    ///
    /// Check `created` before assuming a stash exists - a clean worktree yields
    /// `created=false` with no error and no new entry. Set `includeUntracked` to sweep
    /// untracked files in as well; without it they stay in the worktree. `message` is
    /// optional. Stashing reverts the worktree to HEAD, so this is how work is set
    /// aside before a checkout. New entries land at index 0 and shift every existing
    /// index. Requires `--allow-write`.
    #[tool]
    async fn bonsai_create_stash(
        &self,
        Parameters(args): Parameters<CreateStashArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                let scope = if args.include_untracked {
                    bonsai_core::git::stash::StashScope::AllWithUntracked
                } else {
                    bonsai_core::git::stash::StashScope::All
                };
                bonsai_core::git::stash::create_stash(wd, args.message.as_deref(), scope)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Apply a stash without dropping it; conflicts reported as typed paths.
    ///
    /// The stash survives regardless of outcome, so this is the recoverable option -
    /// `bonsai_pop_stash` also removes it. Branch on the outcome tag: `applied`,
    /// `conflicts` (typed paths to resolve), `appliedPartially`, `notApplied`, or the
    /// reserved-path cases below. Take `index` from `bonsai_list_stashes`; indices
    /// shift after any stash mutation. Requires `--allow-write`.
    ///
    /// If the stash contains Windows-reserved paths (e.g. `NUL`) that cannot be
    /// checked out, the first attempt (`skipReserved` false/omitted) applies
    /// nothing and returns a `reservedPaths` outcome listing them; retry with
    /// `skipReserved: true` to apply the rest, yielding `appliedSkippingReserved`.
    #[tool]
    async fn bonsai_apply_stash(
        &self,
        Parameters(args): Parameters<StashApplyArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::stash::apply_stash(wd, args.index, args.skip_reserved, None)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Apply a stash and drop it on clean success only.
    ///
    /// Same typed outcomes as `bonsai_apply_stash` - `applied`, `conflicts`,
    /// `appliedPartially`, `notApplied`, plus the reserved-path cases - but the entry
    /// is removed on a clean apply, which shifts every remaining index. On anything
    /// less than clean the stash is KEPT, so nothing is lost; re-read
    /// `bonsai_list_stashes` afterwards instead of reusing the old index. Requires
    /// `--allow-write`.
    ///
    /// If the stash contains Windows-reserved paths (e.g. `NUL`) that cannot be
    /// checked out, the first attempt (`skipReserved` false/omitted) applies
    /// nothing and returns a `reservedPaths` outcome listing them; retry with
    /// `skipReserved: true` to apply the rest (`appliedSkippingReserved`). When
    /// any path is skipped the stash is KEPT (not dropped) so nothing is lost.
    #[tool]
    async fn bonsai_pop_stash(
        &self,
        Parameters(args): Parameters<StashApplyArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| {
                bonsai_core::git::stash::pop_stash(wd, args.index, args.skip_reserved, None)
            })
            .await
        {
            Ok(v) => ok_json(&v),
            Err(e) => err_result(e),
        }
    }

    /// Permanently delete one stash entry by index, without applying it.
    ///
    /// This cannot be undone and the stashed changes are unrecoverable - inspect the
    /// entry via `bonsai_list_stashes`, or apply it first, before dropping.
    /// Indices are positional and shift after every drop, so re-read the stack rather
    /// than dropping a second index from the same listing. Requires `--allow-write`.
    /// Use `bonsai_pop_stash` to apply and remove in one step.
    #[tool]
    async fn bonsai_drop_stash(
        &self,
        Parameters(args): Parameters<StashIndexArgs>,
    ) -> CallToolResult {
        match self
            .run_blocking(move |wd| bonsai_core::git::stash::drop_stash(wd, args.index, None))
            .await
        {
            Ok(()) => ok_null(),
            Err(e) => err_result(e),
        }
    }
}
