/**
 * P91 §7.2 — the frontend redactor.
 *
 * The `argsHash` vectors are the CROSS-SIDE contract: they are generated by
 * `src-tauri/src/obs/tests_redact.rs::args_hash_cross_side_vectors` and copied
 * here verbatim. A TS test asserting TS output would be circular.
 *
 * There is deliberately NO test that the two sides agree on an ordinal: §7.2 (c)
 * was struck (a counter cannot agree across sides), and the `ui:` prefix exists
 * precisely so the two namespaces can never be conflated.
 */
import { afterEach, describe, expect, it } from 'vitest';
import {
  argsShape,
  canonicalJson,
  clearSessionSalt,
  hashArgs,
  hashCanonical,
  redactionReady,
  setSessionSalt,
  tagPath,
  tagValue,
} from './redact';

/** Same 16 bytes as `SALT_MOCK` in the Rust test and the mock IPC handler. */
const SALT = '00112233445566778899aabbccddeeff';

/** Copied from the Rust test output — do not edit without re-running it. */
const VECTORS: ReadonlyArray<[string, string]> = [
  ['[]', '2375e1e2'],
  ['[{}]', 'c673fb57'],
  ['["/repo/one",{"path":"src/app.ts"}]', '05c8197b'],
  ['[{"a":1,"b":"zwei"}]', '2502ec22'],
  ['[{"msg":"héllo — ünïcode"}]', '885d657a'],
  ['[{"n":1,"f":1.5,"t":true,"z":null}]', 'ddfacfa0'],
  ['[[1,2,[3,"x"]],"<fn>"]', 'd2d06e48'],
];

afterEach(() => {
  clearSessionSalt();
});

describe('argsHash — cross-side agreement', () => {
  it('matches every Rust-generated vector', () => {
    expect(setSessionSalt(SALT)).toBe(true);
    for (const [canonical, expected] of VECTORS) {
      expect(hashCanonical(canonical), canonical).toBe(expected);
    }
  });

  it('is salt-dependent, so two sessions are not cross-linkable', () => {
    setSessionSalt(SALT);
    const a = hashArgs(['/repo/one']);
    setSessionSalt('ffeeddccbbaa99887766554433221100');
    expect(hashArgs(['/repo/one'])).not.toBe(a);
  });

  it('stays inert with no salt installed (never hashes unsalted)', () => {
    clearSessionSalt();
    expect(redactionReady()).toBe(false);
    expect(hashArgs(['/repo/one'])).toBeUndefined();
    expect(setSessionSalt('')).toBe(false);
    expect(setSessionSalt('not-hex!!')).toBe(false);
  });
});

describe('canonicalJson', () => {
  it('sorts keys recursively so argument order cannot change the hash', () => {
    expect(canonicalJson({ b: 1, a: { d: 2, c: 3 } })).toBe('{"a":{"c":3,"d":2},"b":1}');
    setSessionSalt(SALT);
    expect(hashArgs([{ b: 1, a: 2 }])).toBe(hashArgs([{ a: 2, b: 1 }]));
  });

  it('replaces callbacks, undefined and cycles with fixed placeholders', () => {
    expect(canonicalJson([() => 0])).toBe('["<fn>"]');
    expect(canonicalJson([undefined])).toBe('["<undefined>"]');
    const cyclic: Record<string, unknown> = {};
    cyclic.self = cyclic;
    expect(canonicalJson(cyclic)).toBe('{"self":"<cycle>"}');
  });

  it('formats integers as the Rust vectors expect', () => {
    // The TS canonicalizer is the authority for the WIRE text: `1.0` is `1`.
    expect(canonicalJson([{ n: 1.0 }])).toBe('[{"n":1}]');
  });
});

describe('argsShape', () => {
  it('records key names, types and lengths only — never values', () => {
    const shape = argsShape(['/repo/one', { path: 'src/app.ts' }, [1, 2, 3], null, true, 4]);
    expect(shape).toEqual({
      '0': 'str',
      '1': 'obj:1',
      '2': 'arr:3',
      '3': 'null',
      '4': 'bool',
      '5': 'num',
    });
    expect(JSON.stringify(shape)).not.toContain('app.ts');
  });
});

describe('ordinals (§7.2)', () => {
  it('are ui:-prefixed and stable within a session', () => {
    setSessionSalt(SALT);
    const main = tagValue('ref', 'refs/heads/main');
    expect(main).toMatch(/^ui:ref#\d+$/);
    expect(tagValue('ref', 'refs/heads/main')).toBe(main);
    expect(tagValue('ref', 'refs/heads/feat')).not.toBe(main);
    expect(tagPath('src/components/App.tsx')).toMatch(/^ui:path#\d+\.tsx$/);
    expect(tagValue('repo', 'D:/repos/x')).toMatch(/^ui:repo#\d+$/);
    expect(tagValue('remote', 'https://github.com/o/r.git')).toMatch(/^ui:remote#\d+$/);
  });

  it('differ across sessions, so two files cannot be cross-linked', () => {
    setSessionSalt(SALT);
    const a = tagValue('ref', 'refs/heads/main');
    setSessionSalt('ffeeddccbbaa99887766554433221100');
    expect(tagValue('ref', 'refs/heads/main')).not.toBe(a);
  });

  it('never emits a bare ordinal', () => {
    setSessionSalt(SALT);
    const all = [
      tagValue('ref', 'a'),
      tagValue('path', 'b/c.ts'),
      tagPath('b/c.ts'),
      tagValue('repo', 'd'),
      tagValue('remote', 'e'),
      tagValue('other', 'f'),
    ].join(' ');
    expect(all).not.toMatch(/(^|[^:\w])(ref|path|repo|remote|other)#/);
  });
});
